# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matMult <- function(A, B) {
    .Call(`_stablemap_matMult`, A, B)
}

matInv <- function(A) {
    .Call(`_stablemap_matInv`, A)
}

matSolve <- function(A, B) {
    .Call(`_stablemap_matSolve`, A, B)
}

